# Where things are
source:      .
destination: docs


# Handling Reading
safe:         false
include:      [".htaccess"]
exclude:      ["node_modules", "vendor"]
keep_files:   [".git", ".svn"]
encoding:     "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

